import { useEffect, useState } from 'react';
import { DEFAULT_DATA_GATEWAYS } from '../arfs/gql';
import { usePrivateDrives } from '../state/privateDrives';
import type { FileEntity, ThumbnailVariant } from '../arfs/types';
import { cache } from '../cache/db';
import { computeLocalThumbDimensions, rasterize } from '../arfs/write/thumbnail';
import { Gate } from '../arfs/pool';
import { fileKind } from './format';

const GATEWAY = DEFAULT_DATA_GATEWAYS[0];

/**
 * Bump this whenever `rasterize()`'s actual output changes (a quality fix, a different target
 * size, anything that would make an already-cached blob worse than a fresh one) — it's what tells
 * `cache.getLocalThumb` to treat every blob generated by the old code as a miss instead of serving
 * it forever. Learned the hard way: the halving-downscale fix below shipped once without bumping
 * this, and every already-cached (blurry) thumbnail kept being served as if nothing had changed,
 * since the cache key is just the file's transaction ID and the source image genuinely never
 * changes — only the *generation code* did, which the cache had no way to know on its own.
 */
const LOCAL_THUMB_VERSION = 4;

/**
 * In-flight generations, keyed by data transaction ID — the **promise**, not just a "busy" flag.
 *
 * This was a `Set<string>` that made a second concurrent caller `return null` and give up, which
 * was a real bug: icon/row views are virtualized, so scrolling a tile out of view and back
 * remounts it and re-runs the effect, very often while the first generation is still running. That
 * second caller got `null`, concluded there was nothing better available, and left the small blurry
 * on-chain variant on screen — permanently, since a later remount would hit the same race. Sharing
 * the in-flight promise means every caller gets the same finished thumbnail instead.
 *
 * Same reasoning (and the same fix) as `arfs/crypto/fileData.ts`'s `tagsCache`/`thumbnailCache`,
 * which cache the promise rather than the resolved value for exactly this collapse-duplicates
 * effect. Entries are dropped once settled: a success is served from the persistent cache from
 * then on, and a failure stays retryable rather than being remembered as permanent.
 */
const inFlightBackfills = new Map<string, Promise<Blob | null>>();

/**
 * Caps how many full-resolution decodes run at once, across every tile on screen.
 *
 * Decoding is the memory-heavy step: a 12MP photo becomes a ~48MB bitmap, plus intermediate
 * canvases while it's halved down. The large-tile icon view can mount ~35 tiles at once, each of
 * which may need a generation, so uncapped that's well over a gigabyte in flight — past what a
 * phone browser tolerates (iOS in particular enforces a hard total-canvas-memory ceiling, beyond
 * which canvas creation just fails). Only the decode is gated; fetching the compressed bytes stays
 * parallel, since that's cheap in memory and where most of the wall-clock time goes.
 */
const decodeGate = new Gate(2);

/**
 * Confirmed live (2026-08-16) against a real mainnet transaction that Arweave gateways ignore
 * `Range` headers entirely and always return the full body (a 20KB range request against a
 * 2.6MB file still transferred all 2.6MB) — so there is no cheaper way to get *any* pixel data
 * for a file with no real thumbnail than fetching the whole thing once. This backfill is the
 * next best thing: pay that full-fetch cost once per file, ever, and cache a small JPEG locally
 * so every later view — this session or a future one, this drive or a revisit after a reload —
 * is instant instead of repeating it.
 *
 * `fetch()`, not reusing the `<img>` element that triggered this: an `<img>`-sourced canvas draw
 * needs `crossorigin` set to avoid tainting the canvas, and that's a real risk of breaking image
 * display outright on any gateway that doesn't happen to send CORS headers (confirmed present on
 * arweave.net and permagate.io, not independently confirmed for every configured gateway). A
 * plain `fetch()` has no such requirement, and in practice costs nothing extra: it's the same URL
 * the `<img>` tag just requested, and these gateways send long-lived `cache-control` headers, so
 * this is a browser HTTP-cache hit, not a second real network round trip.
 */
function backfillLocalThumbnail(dataTxId: string, url: string): Promise<Blob | null> {
  const existing = inFlightBackfills.get(dataTxId);
  if (existing) return existing;
  const generation = generateLocalThumbnail(dataTxId, url);
  inFlightBackfills.set(dataTxId, generation);
  void generation.finally(() => inFlightBackfills.delete(dataTxId));
  return generation;
}

async function generateLocalThumbnail(dataTxId: string, url: string): Promise<Blob | null> {
  try {
    const blob = await (await fetch(url)).blob();
    // Decode + downscale under `decodeGate`; the network fetch above deliberately isn't gated.
    const thumbBlob = await decodeGate.run(async () => {
      // `imageOrientation: 'from-image'` — see the matching comment in `arfs/write/thumbnail.ts`'s
      // `generateImageThumbnail`. Without it, a real phone photo's EXIF rotation is silently
      // ignored here even though a plain `<img>` of the same file honors it — the generated
      // thumbnail would come out rotated relative to the image it's a small version of.
      const bitmap = await createImageBitmap(blob, { imageOrientation: 'from-image' });
      try {
        // Short-side sizing, not the on-chain long-side cap — see `LOCAL_THUMB_SHORT_SIDE`. This is
        // the difference between a thumbnail with enough pixels for a large tile and one that gets
        // upscaled ~1.3-1.75x on display, which is what actually reads as "blurry".
        const { width, height } = computeLocalThumbDimensions(bitmap.width, bitmap.height);
        // `rasterize` (shared with the upload path) downscales via repeated halving rather than one
        // big single-pass draw, which looks soft even at the canvas API's "high" smoothing.
        return await rasterize(bitmap, width, height);
      } finally {
        bitmap.close();
      }
    });
    if (thumbBlob) {
      await cache.putLocalThumb(dataTxId, thumbBlob, LOCAL_THUMB_VERSION);
      return thumbBlob;
    }
    return null;
  } catch {
    // Best-effort — the next view just falls back to the same full fetch this one just did,
    // exactly today's behavior, not a regression.
    return null;
  }
}

/**
 * Is an existing on-chain thumbnail variant big enough for the box it's about to be painted into?
 *
 * The UI uses `object-cover` in a square box, so the variant's **short** side is what must cover
 * `displayPx` at the device's real pixel density. A variant that fails this gets displayed anyway
 * (it's already there and it's fast), but also triggers a one-time local upgrade so the *next*
 * view is sharp — see `useThumbnailUrl`. Being display-size aware is what keeps that upgrade from
 * firing at list scale: a 480px variant is comfortably enough for a 32px list row or a small tile,
 * and only falls short in the large-tile icon view, which is exactly where the user has asked for
 * a big image and the extra one-time fetch is justified.
 */
function variantCovers(variant: ThumbnailVariant, displayPx: number): boolean {
  const shortSide = Math.min(variant.width, variant.height);
  if (!shortSide) return false;
  return shortSide >= displayPx * (window.devicePixelRatio || 1);
}

/**
 * Resolves a file to a small-image URL for the row list, preferring a real ArDrive-format
 * thumbnail when the file has one (same shape `Preview.tsx`'s `usePreviewUrl` uses: a direct
 * gateway URL for public, a decrypted `blob:` URL for private).
 *
 * When there's no thumbnail: a public image generates one locally from the full image the first
 * time it's ever viewed (`backfillLocalThumbnail` below) and caches it, so every later view —
 * this file, anywhere, any session — is instant. The full image is never painted directly; see
 * that function and the no-variant branch for why. A private image without one stays icon-only
 * rather than
 * eagerly decrypting the full file just to paint a row — this is deliberately how ArDrive itself
 * behaves too, not a corner this app cuts on its own: a real thumbnail variant is generated for
 * every image at upload time (both by ArDrive and by this app's own upload path, see M5), so in
 * practice a private image with no thumbnail is the rare case, not the common one. If a thumbnail
 * still isn't showing for a file that should have one, that's a bug in fetching/decrypting the
 * variant, not a reason to fall back to decrypting the whole file — see the console for
 * `[sonar] thumbnail decrypt failed` if that happens.
 */
export function useThumbnailUrl(
  file: FileEntity,
  /** CSS px of the square box this will be painted into — see `variantCovers`. */
  displayPx: number,
): { url: string | null; loading: boolean } {
  const getDecryptContext = usePrivateDrives((s) => s.getDecryptContext);
  const [url, setUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const kind = fileKind(file.dataContentType, file.name);
  // Prefer the *largest* available variant, not the smallest. The old "smallest is fine for a
  // small row slot" reasoning only held while every consumer was a small row slot; the large icon
  // tile needs every pixel it can get, and picking the smallest actively throws away detail that
  // is already sitting on chain for free. Nothing known produces multiple variants today, so in
  // practice this changes nothing — it just stops being wrong the day something does.
  const variant = file.thumbnail?.variants.length
    ? file.thumbnail.variants.reduce((largest, v) => (v.width > largest.width ? v : largest))
    : null;
  const variantTxId = variant?.txId ?? null;
  // A variant too small for this box still paints immediately (fast), but also triggers the
  // one-time local upgrade below so the next view is sharp.
  const variantIsEnough = variant ? variantCovers(variant, displayPx) : false;

  useEffect(() => {
    // A just-uploaded file (height: null) almost never has its bytes on a gateway yet — Turbo
    // confirms instantly but real propagation lags well behind that. Attempting the fetch anyway
    // just means a broken-image flash (public) or a wasted decrypt attempt (private); the row's
    // "Processing" badge already tells the user why nothing is showing, so skip straight to the
    // icon fallback here and let it resolve normally once a real sync confirms the file.
    if (kind !== 'image' || file.height === null) {
      setUrl(null);
      setLoading(false);
      return undefined;
    }

    if (variantTxId) {
      if (file.privacy === 'public') {
        const variantUrl = `${GATEWAY}/${variantTxId}`;

        // Big enough for this box — nothing more to do, and no extra network at all.
        if (variantIsEnough) {
          setUrl(variantUrl);
          setLoading(false);
          return undefined;
        }

        // Too small for this box (the common case for a 480px on-chain variant in a large icon
        // tile). The on-chain bytes can never be improved — they're permanent — so the only way to
        // get a sharp tile is a locally generated one from the full image. Paint the variant right
        // away so there's no blank slot, then upgrade in place once the better version exists.
        setUrl(variantUrl);
        setLoading(false);
        let swapped: string | null = null;
        let dropped = false;

        void cache.getLocalThumb(file.dataTxId, LOCAL_THUMB_VERSION).then(async (cached) => {
          const better = cached ?? (await backfillLocalThumbnail(file.dataTxId, `${GATEWAY}/${file.dataTxId}`));
          if (!better || dropped) return;
          swapped = URL.createObjectURL(better);
          setUrl(swapped);
        });

        return () => {
          dropped = true;
          if (swapped) URL.revokeObjectURL(swapped);
        };
      }

      const ctx = getDecryptContext(file.driveId);
      if (!ctx) {
        setUrl(null);
        setLoading(false);
        return undefined;
      }

      setUrl(null);
      setLoading(true);
      let cancelled = false;
      let objectUrl: string | null = null;

      (async () => {
        const { fetchAndDecryptThumbnail } = await import('../arfs/crypto/fileData');
        const fileKey = await ctx.getFileKey(file.entityId);
        const blob = await fetchAndDecryptThumbnail(variantTxId, fileKey);
        if (cancelled) return;
        objectUrl = URL.createObjectURL(blob);
        setUrl(objectUrl);
        setLoading(false);
      })().catch((err) => {
        if (cancelled) return;
        setLoading(false);
        // Was silent before this. It fires per-row for every visible private image with a
        // thumbnail variant, so a real gateway/decrypt problem here is easy to mistake for
        // "private thumbnails just don't work" instead of what it actually is.
        console.warn(`[sonar] thumbnail decrypt failed for "${file.name}" (${file.entityId}):`, err);
      });

      return () => {
        cancelled = true;
        if (objectUrl) URL.revokeObjectURL(objectUrl);
      };
    }

    if (file.privacy !== 'public') {
      setUrl(null);
      setLoading(false);
      return undefined;
    }

    // No thumbnail variant at all. Serve the locally generated one — from cache if it exists,
    // otherwise generate it now.
    //
    // Deliberately **never** points the <img> at the full-size original, which is what this used
    // to do. A multi-MB photo assigned straight to `src` gets painted by the browser *as it
    // streams* — a partially-decoded JPEG/PNG squeezed into a small tile renders as torn bands of
    // half-image, which reads as "scrambled", not as loading. Waiting for the generated thumbnail
    // shows the fallback icon a moment longer and then one clean, sharp image, and costs no extra
    // network: the generation is fetching that exact URL anyway.
    setUrl(null);
    setLoading(true);
    let cancelled = false;
    let objectUrl: string | null = null;

    void (async () => {
      const fullUrl = `${GATEWAY}/${file.dataTxId}`;
      const cached = await cache.getLocalThumb(file.dataTxId, LOCAL_THUMB_VERSION);
      const blob = cached ?? (await backfillLocalThumbnail(file.dataTxId, fullUrl));
      if (cancelled) return;
      if (blob) {
        objectUrl = URL.createObjectURL(blob);
        setUrl(objectUrl);
      } else {
        // Generation genuinely failed (a format `createImageBitmap` can't decode, a decode error).
        // Fall back to the original rather than showing nothing — the pre-existing behavior, now
        // reserved for the case where it's the only option instead of being the normal path.
        setUrl(fullUrl);
      }
      setLoading(false);
    })();

    return () => {
      cancelled = true;
      if (objectUrl) URL.revokeObjectURL(objectUrl);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    kind,
    variantTxId,
    variantIsEnough,
    file.privacy,
    file.driveId,
    file.entityId,
    file.dataTxId,
    file.height,
  ]);

  return { url, loading };
}

/**
 * A row-list or icon-tile image slot: a real image when one resolves, the caller's icon otherwise.
 *
 * `displayPx` is the CSS size of the square box this paints into (32 for a list row's icon slot,
 * the tile size in icon view). It's what decides whether an existing on-chain thumbnail has enough
 * pixels or needs a one-time local upgrade — see `variantCovers`.
 */
export function RowThumbnail({
  file,
  fallback,
  displayPx,
}: {
  file: FileEntity;
  fallback: React.ReactNode;
  displayPx: number;
}) {
  const { url } = useThumbnailUrl(file, displayPx);
  if (!url) return <>{fallback}</>;
  return <img src={url} alt="" loading="lazy" className="w-full h-full object-cover rounded-md" />;
}
