import 'fake-indexeddb/auto';
import { beforeEach, describe, expect, it } from 'vitest';
import { deleteDB, openDB } from 'idb';
import { __resetCacheForTests, cache } from './db';

const V = 1;

beforeEach(async () => {
  await cache.clear();
  __resetCacheForTests();
});

describe('local thumbnail cache', () => {
  it('returns undefined for a transaction that was never cached', async () => {
    expect(await cache.getLocalThumb('nonexistent-tx', V)).toBeUndefined();
  });

  it('round-trips a blob keyed by data transaction id', async () => {
    const blob = new Blob(['fake jpeg bytes'], { type: 'image/jpeg' });
    await cache.putLocalThumb('tx-abc', blob, V);

    const stored = await cache.getLocalThumb('tx-abc', V);
    expect(stored).toBeDefined();
    expect(stored!.type).toBe('image/jpeg');
    expect(await stored!.text()).toBe('fake jpeg bytes');
  });

  it('keeps entries for different transactions independent', async () => {
    await cache.putLocalThumb('tx-1', new Blob(['one']), V);
    await cache.putLocalThumb('tx-2', new Blob(['two']), V);

    expect(await (await cache.getLocalThumb('tx-1', V))!.text()).toBe('one');
    expect(await (await cache.getLocalThumb('tx-2', V))!.text()).toBe('two');
  });

  it('overwrites a stale entry when put again under the same key', async () => {
    await cache.putLocalThumb('tx-1', new Blob(['old']), V);
    await cache.putLocalThumb('tx-1', new Blob(['new']), V);
    expect(await (await cache.getLocalThumb('tx-1', V))!.text()).toBe('new');
  });

  it('is wiped by cache.clear() along with everything else', async () => {
    await cache.putLocalThumb('tx-1', new Blob(['one']), V);
    await cache.clear();
    expect(await cache.getLocalThumb('tx-1', V)).toBeUndefined();
  });

  it('treats an entry generated by an older version as a miss, not a stale hit', async () => {
    // Exactly the bug this field exists to prevent: the generation algorithm changed (a real
    // blur fix), but the cache key alone can't tell "same file, different code" from "same file,
    // same code" — an old blob must not keep being served forever just because the source
    // transaction itself never changes.
    await cache.putLocalThumb('tx-1', new Blob(['made by v1']), 1);
    expect(await cache.getLocalThumb('tx-1', 2)).toBeUndefined();
  });

  it('a newer put for the same key replaces an older version outright', async () => {
    await cache.putLocalThumb('tx-1', new Blob(['old algorithm']), 1);
    await cache.putLocalThumb('tx-1', new Blob(['new algorithm']), 2);
    expect(await (await cache.getLocalThumb('tx-1', 2))!.text()).toBe('new algorithm');
    expect(await cache.getLocalThumb('tx-1', 1)).toBeUndefined();
  });
});

describe('upgrading from version 2', () => {
  it('forgets sync watermarks but keeps cached bodies', async () => {
    // A v2 database as a browser that synced under the old gateway order would have it.
    __resetCacheForTests();
    await deleteDB('swiftdrive');
    const v2 = await openDB('swiftdrive', 2, {
      upgrade(db) {
        db.createObjectStore('txBodies', { keyPath: 'txId' });
        const entities = db.createObjectStore('entities', { keyPath: 'metadataTxId' });
        entities.createIndex('by-drive', 'driveId');
        entities.createIndex('by-owner', 'owner');
        db.createObjectStore('syncState', { keyPath: 'key' });
        db.createObjectStore('localThumbs', { keyPath: 'dataTxId' });
      },
    });
    await v2.put('syncState', { key: 'drive:abc', lastHeight: 1_500_000, updatedAt: 0 });
    await v2.put('txBodies', { txId: 'tx-1', body: '{"name":"a.txt"}' });
    v2.close();

    expect(await cache.getSync('drive:abc')).toBeUndefined();
    expect(await cache.getBody('tx-1')).toBe('{"name":"a.txt"}');
  });
});
